[추가] ViewModel 추가, App Dagger Hilt 적용 및 뷰모델 테스트 코드 추가
빌드에러 발생

D:\android_workspace\github\parkchan\CleanArchitureStudy\app\build\generated\source\kapt\debug\com\chan\moviesearcher\MyApplication_HiltComponents.java:127: error: [Dagger/MissingBinding] com.chan.moviesearcher.domain.repository.MovieSearchRepository cannot be provided without an @Provides-annotated method.
  public abstract static class SingletonC implements MyApplication_GeneratedInjector,
                         ^
      com.chan.moviesearcher.domain.repository.MovieSearchRepository is injected at
          com.chan.moviesearcher.di.MovieSearchUseCaseModule.provideMovieSearchUseCase(repository)
      com.chan.moviesearcher.domain.MovieSearchUseCase is injected at
          com.chan.moviesearcher.viewmodel.MovieSearchViewModel(useCase)
      com.chan.moviesearcher.viewmodel.MovieSearchViewModel is injected at
          com.chan.moviesearcher.ScrollingActivity.viewModel
      com.chan.moviesearcher.ScrollingActivity is injected at
          com.chan.moviesearcher.ScrollingActivity_GeneratedInjector.injectScrollingActivity(com.chan.moviesearcher.ScrollingActivity) [com.chan.moviesearcher.MyApplication_HiltComponents.SingletonC → com.chan.moviesearcher.MyApplication_HiltComponents.ActivityRetainedC → com.chan.moviesearcher.MyApplication_HiltComponents.ActivityC]
  The following other entry points also depend on it:
      dagger.hilt.android.internal.lifecycle.HiltView